# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hello_world <- function() {
    invisible(.Call(`_RcppExample_hello_world`))
}

std_vector_example <- function() {
    .Call(`_RcppExample_std_vector_example`)
}

arma_outerproduct <- function(x) {
    .Call(`_RcppExample_arma_outerproduct`, x)
}

arma_3_matrices <- function(x) {
    .Call(`_RcppExample_arma_3_matrices`, x)
}

arma_innerproduct <- function(x) {
    .Call(`_RcppExample_arma_innerproduct`, x)
}

arma_fastLm <- function(X, y) {
    .Call(`_RcppExample_arma_fastLm`, X, y)
}

eigen_2_matrices <- function() {
    .Call(`_RcppExample_eigen_2_matrices`)
}

