# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Hello world
#' 
#' @export
hello_world <- function() {
    invisible(.Call(`_RcppExample_hello_world`))
}

std_vector_example <- function() {
    .Call(`_RcppExample_std_vector_example`)
}

arma_outerproduct <- function(x) {
    .Call(`_RcppExample_arma_outerproduct`, x)
}

#' Outer products multiplied by different integers (1, ..., 3)
#' 
#' @param x a vector
#' @export
arma_3_matrices <- function(x) {
    .Call(`_RcppExample_arma_3_matrices`, x)
}

arma_innerproduct <- function(x) {
    .Call(`_RcppExample_arma_innerproduct`, x)
}

arma_fastLm <- function(X, y) {
    .Call(`_RcppExample_arma_fastLm`, X, y)
}

#' Create two matrices and return them in a list
#' @export
eigen_2_matrices <- function() {
    .Call(`_RcppExample_eigen_2_matrices`)
}

